DROP TABLE IF EXISTS USER_EXA;
CREATE TABLE USER_EXA (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  ap VARCHAR(250) NOT NULL,
  username VARCHAR(250) NOT NULL,
  address VARCHAR(250) DEFAULT NULL,
  email VARCHAR(250) DEFAULT NULL,
);

INSERT INTO USER_EXA
VALUES(10001,'Zaragoza', 'Ale', 'Troncoso', 'Ale@gmail');

INSERT INTO USER_EXA
VALUES(10002,'Gomez', 'Jorge', 'Azucena', 'Jorge@gmail');


DROP TABLE IF EXISTS CONDICION;
CREATE TABLE CONDICION (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  ID_GENERADO VARCHAR(12) NOT NULL,
  TIPO VARCHAR(250) NOT NULL,
  TITULO VARCHAR(250) NOT NULL,
  DESCRIPCION VARCHAR(250) NOT NULL,
  TEXTO VARCHAR(250) DEFAULT NULL,
  ESTATUS INT(3) NOT NULL
);

INSERT INTO CONDICION
VALUES (10001, 'COBE00010000', 'COBERTURA', 'SEGURO AUTO', 'SEGURO DE AUTO AMPLIO', 'TEXTO EN NEGRITAS', 1);

INSERT INTO CONDICION
VALUES (10002, 'SERV00010000', 'SERVICIO', 'SEGURO MOTOCICLETA', 'SEGURO DE MOTOCICLETA AMPLIO', 'TEXTO EN NEGRITAS MOTOCICLETA', 1);