




INSERT INTO CONDICION (id, ID_GENERADO,tipo,titulo,descripcion, texto, estatus)
VALUES (10001, 'COBE00010000', 'COBERTURA', 'SEGURO AUTO', 'SEGURO DE AUTO AMPLIO', 'TEXTO EN NEGRITAS', 1);

INSERT INTO CONDICION  (id, ID_GENERADO,tipo,titulo,descripcion, texto, estatus)
VALUES (10002, 'SERV00010000', 'SERVICIO', 'SEGURO MOTOCICLETA', 'SEGURO DE MOTOCICLETA AMPLIO', 'TEXTO EN NEGRITAS MOTOCICLETA', 1);

--Insert de usuarios
insert into usuarios (OID,CVEUSUARIO, CVEUSUARIO_LDAP, NOMCOMPLETO,EMAIL1, ESACTIVO )
  VALUES (1,'lreyesve', 'lreyesve-ldap', 'Luis Reyes Velasco', 'lreyesve@capgemini.com', 1);
insert into usuarios (OID,CVEUSUARIO, CVEUSUARIO_LDAP, NOMCOMPLETO,EMAIL1, ESACTIVO )
  VALUES (2,'jgomez', 'jgomez-ldap', 'Jorge Gomez', 'jgomez@capgemini.com', 1);

--insert de roles modulo
insert into ROLESMODULO (OID,CVEROL,NOMROL,DESCROL)
  VALUES (1,'ADMIN', 'ADMINISTRADOR', 'ADMINISTRADOR DEL SISTEMA');
insert into ROLESMODULO (OID,CVEROL,NOMROL,DESCROL)
  VALUES (2,'USER', 'USUARIO', 'USUARIO DEL SISTEMA');

--INSERT INTERMEDIO
INSERT INTO usuariosroles (OID,USUARIOS_OID, ROLESMODULO_OID)
VALUES (1,SELECT OID FROM USUARIOS WHERE CVEUSUARIO = 'lreyesve', SELECT OID FROM ROLESMODULO WHERE CVEROL = 'ADMIN' );
INSERT INTO usuariosroles (OID, USUARIOS_OID, ROLESMODULO_OID)
VALUES (2,SELECT OID FROM USUARIOS WHERE CVEUSUARIO = 'jgomez', SELECT OID FROM ROLESMODULO WHERE CVEROL = 'ADMIN' );
